query FindUserByGoogleId($googleId: String!) @auth(level: USER) {
  users(where: { googleId: { eq: $googleId } }, limit: 1) {
    id
    googleId
    displayName
    email
  }
}

query GetMySubscriptions($userId: UUID!) @auth(level: USER) {
  subscriptionTypes(where: { userId: { eq: $userId } }) {
    user @redact {
      googleId
    }
    listOrder
    podcast {
      id
      title
      feedUrl
      imageUrl
      author
      categories
    }
  }
}

query GetRecommendations($feedUrl: String!) @auth(level: PUBLIC, insecureReason: "Recommendations are public anonymous data") {
  subscriptionTypes(where: { podcast: { feedUrl: { eq: $feedUrl } } }) {
    user {
      subscriptionTypes_on_user {
        podcast {
          id
          title
          imageUrl
          feedUrl
          author
          categories
        }
      }
    }
  }
}

query GetPodcastByFeedUrl($feedUrl: String!) @auth(level: PUBLIC, insecureReason: "Podcasts are public data") {
  podcasts(where: { feedUrl: { eq: $feedUrl } }, limit: 1) {
    id
    title
    feedUrl
    imageUrl
  }
}
