type User @table {
  googleId: String!
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
}

type Podcast @table {
  title: String!
  feedUrl: String!
  createdAt: Timestamp!
  description: String
  imageUrl: String
  author: String
  categories: [String]
}

type Episode @table {
  podcast: Podcast
  title: String!
  audioUrl: String!
  publishedAt: Timestamp!
  duration: Int64!
  description: String
  imageUrl: String
}

type SubscriptionType @table(key: ["user", "podcast"]) {
  user: User!
  podcast: Podcast!
  subscribedAt: Timestamp!
  listOrder: Int
}

type ListenHistory @table(key: ["user", "episode"]) {
  user: User!
  episode: Episode!
  listenedAt: Timestamp!
  progressSeconds: Int64!
  finishedListening: Boolean
}
